version: '3'
services:
  mysql:
    container_name: sns-db
    image: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./${USEDB}:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: wp
    networks:
      - sns_network
  wordpress:
    container_name: sns-wp-php${PHPV}
    build: ./${PHPV}/
    depends_on:
      - mysql
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: wp
    volumes:
      - ../:/var/www/html/wp-content/plugins/scripts-n-styles/
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./debug.log:/var/www/html/wp-content/debug.log
    networks:
      - sns_network
networks:
  sns_network:
volumes:
  db_data:
